version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        user: dev
        uid: 1000
    container_name: ideas-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - ideas-network
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ideas
      DB_USERNAME: ideas
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      REDIS_PORT: 6379

  nginx:
    image: nginx:alpine
    container_name: ideas-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - ideas-network

  mysql:
    image: mysql:8.0
    container_name: ideas-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ideas-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - ideas-network

networks:
  ideas-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: